os: linux
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - blog-resource
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  strategy: git
  provider: pages
  cleanup: false
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: public