os: linux
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - blog-resource
script:
  - hexo generate # generate static files
deploy:
  strategy: git
  provider: pages
  cleanup: false
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: blog-resource
  target_branch: master
  local_dir: public